- name: Install Docker engine
  hosts: "ubuntu"
  become: true
  tags:
    - install
    - docker
  tasks:
  - name: Set Ubuntu release codename
    set_fact:
      ubuntu_release_codename: "{{ ansible_distribution_release }}"
    debug:
      var: ubuntu_release_codename

  - name: install dependencies
    apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: present
      update_cache: true
    become: true

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      filename: docker 
      repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_release_codename }} stable
      state: present

  - name: Update apt cache
    apt:
      update_cache: yes
    become: true

  - name: install docker engine
    apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      state: present
      update_cache: true
    become: true

  - name: test docker
    command: docker info
    become: true
