- name: Install DuckDNS
  hosts: "ubuntu"
  become: true
  vars:
    duckdns_domain: sshawn
  vars_files:
    - ../secret.yml
  tasks:
    - name: Install curl package
      package:
        name: curl
        state: present

    - name: Create DuckDNS directory
      file:
        path: ~/duckdns
        state: directory
        mode: '0700'

    - name: Create Duck.sh script
      copy:
        dest: ~/duckdns/duck.sh
        content: |
          #!/bin/bash
          echo url="https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip=" | curl -k -o ~/duckdns/duck.log -K -
        mode: '0700'

    - name: Set up cron job for DuckDNS
      cron:
        name: DuckDNS Update
        minute: '*/5'
        job: "~/duckdns/duck.sh >/dev/null 2>&1"

