- name: Git setup
  hosts: "ubuntu"
  become: true
  tasks:
  - name: Git personal setup email
    git_config:
      name: user.email
      scope: global
      value: "l@sshawn.com"
    tags:
    - git-personal
  - name: Git personal setup name
    git_config:
      name: user.name
      scope: global
      value: "lsshawn"
    tags:
    - git-personal
