- name: Install MariaDB Docker and configure data directory
  hosts: "ubuntu"
  become: true
  vars_files:
    - ../secret.yml
  tasks:
    - name: Create MariaDB data directory
      file:
        path: /mnt/external1/mariadb
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      tags:
        - mariadb

    - name: Run MariaDB Docker container
      docker_container:
        name: mariadb
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
        volumes:
          - /mnt/external1/mariadb:/var/lib/mysql
        restart_policy: always
      tags:
        - mariadb

