- name: Install Zsh, Oh My Zsh, and zsh-autosuggestions
  hosts: "*"
  become: true
  vars:
    zsh_plugins:
      - zsh-autosuggestions
  tasks:
    - name: Install Zsh
      apt:
        name: zsh
        state: present

    - name: Set Zsh as the default shell
      command: chsh -s /usr/bin/zsh "{{ ansible_user }}"
      args:
        creates: /home/{{ ansible_user }}/.zshrc

    - name: Change current user shell
      user:
        name: "{{ ansible_ssh_user }}"
        shell: /bin/zsh
      become: yes

    - name: Remove existing oh-my-zsh folder
      file:
        path: "/home/{{ ansible_user }}/.oh-my-zsh"
        state: absent
      become: true
      

    - name: Clone Oh My Zsh repository
      ansible.builtin.git:
        repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
        dest: /home/{{ ansible_user}}/.oh-my-zsh
        depth: 1

    - name: Copy the default Oh My Zsh configuration file
      ansible.builtin.copy:
        src: /home/{{ ansible_user}}/.oh-my-zsh/templates/zshrc.zsh-template
        dest: /home/{{ ansible_user}}/.zshrc

    - name: Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "/home/{{ ansible_user }}/.oh-my-zsh/plugins/zsh-autosuggestions"
      tags: zsh_plugins

    - name: Update Oh My Zsh plugins
      lineinfile:
        dest: "/home/{{ ansible_user }}/.zshrc"
        regexp: '^plugins='
        line: 'plugins=(zsh-autosuggestions)'
        state: present
        backup: yes
      tags: zsh_plugins

